DROP TABLE movies IF EXISTS;

CREATE TABLE movies (
    id INT NOT NULL AUTO_INCREMENT,
    movieId VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    director VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)